/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

// Your description goes here...

#include "Riostream.h"

#include "SpPol2.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include <math.h>
#include "TMath.h"

 SpPol2::SpPol2(const char *name, const char *title,
                        RooAbsReal& _x,
                        RooAbsReal& _c1,
                        RooAbsReal& _c2) :
   RooAbsPdf(name,title),
   x("x","x",this,_x),
   c1("c1","c1",this,_c1),
   c2("c2","c2",this,_c2)
 {
 }


 SpPol2::SpPol2(const SpPol2& other, const char* name) :
   RooAbsPdf(other,name),
   x("x",this,other.x),
   c1("c1",this,other.c1),
   c2("c2",this,other.c2)
 {
 }


 Double_t SpPol2::evaluate() const
 {
   return (x*(TMath::Power(x-c1*4, 3))); //Abel Polynomial Order 3 fn(x) = x(x- an)^n-1
 }
