// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in "/Users/kunal/analysis/diMuon/Mar20_psi2S/Tuning MC/tuning/FinalPlots/./GetAccEffi.C";

#endif
