/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

// Your description goes here...

#include "Riostream.h"

#include "Pol2.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include <math.h>
#include "TMath.h"

 Pol2::Pol2(const char *name, const char *title,
                        RooAbsReal& _x,
                        RooAbsReal& _c1,
                        RooAbsReal& _c2) :
   RooAbsPdf(name,title),
   x("x","x",this,_x),
   c1("c1","c1",this,_c1),
   c2("c2","c2",this,_c2)
 {
 }


 Pol2::Pol2(const Pol2& other, const char* name) :
   RooAbsPdf(other,name),
   x("x",this,other.x),
   c1("c1",this,other.c1),
   c2("c2",this,other.c2)
 {
 }


 Double_t Pol2::evaluate() const
 {
   return ((1 + c1*x + c2*x*x));
 }
