/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

// Your description goes here...

#include "Riostream.h"

#include "CebPol2.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include <math.h>
#include "TMath.h"

 CebPol2::CebPol2(const char *name, const char *title,
                        RooAbsReal& _x,
                        RooAbsReal& _c1,
                        RooAbsReal& _c2) :
   RooAbsPdf(name,title),
   x("x","x",this,_x),
   c1("c1","c1",this,_c1),
   c2("c2","c2",this,_c2)
 {
 }


 CebPol2::CebPol2(const CebPol2& other, const char* name) :
   RooAbsPdf(other,name),
   x("x",this,other.x),
   c1("c1",this,other.c1),
   c2("c2",this,other.c2)
 {
 }


 Double_t CebPol2::evaluate() const
 {
   return ((c1*x*x -c2));
 }
