/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef CEBPOL3
#define CEBPOL3

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

class CebPol3 : public RooAbsPdf {
public:
  CebPol3() {} ;
  CebPol3(const char *name, const char *title,
	      RooAbsReal& _x,
        RooAbsReal& _c1,
	      RooAbsReal& _c2);
  CebPol3(const CebPol3& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new CebPol3(*this,newname); }
  inline virtual ~CebPol3() { }

protected:

  RooRealProxy x ;
  RooRealProxy c1 ;
  RooRealProxy c2 ;

  Double_t evaluate() const ;

private:

  ClassDef(CebPol3,2) // Your description goes here...
};

#endif
