/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef POL1
#define POL1

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

class Pol1 : public RooAbsPdf {
public:
  Pol1() {} ;
  Pol1(const char *name, const char *title,
	      RooAbsReal& _x,
        RooAbsReal& _c1,
	      RooAbsReal& _c2);
  Pol1(const Pol1& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new Pol1(*this,newname); }
  inline virtual ~Pol1() { }

protected:

  RooRealProxy x ;
  RooRealProxy c1 ;
  RooRealProxy c2 ;

  Double_t evaluate() const ;

private:

  ClassDef(Pol1,2) // Your description goes here...
};

#endif
