/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef CEBPOL2
#define CEBPOL2

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

class CebPol2 : public RooAbsPdf {
public:
  CebPol2() {} ;
  CebPol2(const char *name, const char *title,
	      RooAbsReal& _x,
        RooAbsReal& _c1,
	      RooAbsReal& _c2);
  CebPol2(const CebPol2& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new CebPol2(*this,newname); }
  inline virtual ~CebPol2() { }

protected:

  RooRealProxy x ;
  RooRealProxy c1 ;
  RooRealProxy c2 ;

  Double_t evaluate() const ;

private:

  ClassDef(CebPol2,2) // Your description goes here...
};

#endif
